---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    Arturo Ordaz-Gutierrez because clearly has a solid understanding of all of the learning targets.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    Joins were hard for me to understand at first because I had to visualize what was going on.

3.  What was the easiest part of the class for you? Explain why.

    The simulations were the easiest because it was intuitive to just say what sort of distribution you want, how big, etc.

4.  What part of the class surprised or interested you the most? Explain why.

    Lab 5 was interesting because we were working towards the goal of finding the murderer unlike other labs that had less of a main goal.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    It's easy to just find the answers online, but it's important to understand the code you are writing.
